### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by davidberra** [Hypertopic/LaSuli#67] opened 2019-02-11 11:43 UTC
Hi,

so after having used Lasuli without problems for months, I noticed my FireFox got updated. I restored ESR 52.9 version, installed the Lasuli add-on, but cannot open it anymore. Lasuli won't show up under View / SideBar anymore; instead, I see an icon on FF toolbar. When clicking on it, an error occour, and the icon gets flagged with an 'err' sign. 

Here is the error:

TypeError: window.location is null  ima3.js:246:935
Ad error: AdError 901: An unexpected error occurred within the VPAID creative. Refer to the inner error for more info. Caused by: Error: Error: 303  allscriptIMA.min.js:14
write event error  iframe_video_loader.js:556
NS_ERROR_NOT_INITIALIZED:  client.js:32
browser.sidebarAction is undefined  background.js:186
NS_ERROR_NOT_INITIALIZED:  client.js:32
NS_ERROR_NOT_INITIALIZED:  client.js:32
NS_ERROR_NOT_INITIALIZED:  client.js:32
NS_ERROR_NOT_INITIALIZED:  client.js:32

**Comment by benel** [comment] 2019-02-11 13:00
Thank you for feedback.

Since we never included any ad-paid video in LaSuli, I suppose the error is not caused by LaSuli itself but by another extension. You could try to disable other extensions and test if the problem continues.

As for the installation of LaSuli in modern Firefox versions, you could have a look at Firefox 3. It is not yet feature-complete but it has been successfully used by 125 students last semester.

**Comment by davidberra** [comment] 2019-02-12 11:29
Thanks for the prompt reply!  

Somehow I managed to have Lasuli (3) installed, however can't figure out how it works : ) e.g. can't see any button to set connection configuration etc.; it mentions some whitelists; can't login with our credentials... 

is there any documentation?

**Comment by davidberra** [comment] 2019-02-14 15:53
alternatively, how can I install the previous version of Lasuli?

**Comment by benel** [comment] 2019-02-16 10:45
The previous version is still there: 
https://hypertopic.s3.amazonaws.com/lasuli.xpi

**Comment by benel** [comment] 2019-02-16 10:45
The previous version is still there:
https://hypertopic.s3.amazonaws.com/lasuli.2.xpi

**Comment by triinuerik** [comment] 2019-04-04 11:27
Hi David,

Your issue will be dealt with when we do the next release. There will be added functionality of customising your annotation service. Hopefully then your problem will be solved.

To give more information, whitelisted sites are sites that you allow the extension to modify, that means the pages you wish to use LaSuli with. With the next release, adding more sites will be made possible.

**Comment by benel** [comment] 2019-05-28 16:33
Hi @davidberra!
A new version of LaSuli has been released with the following features:
- change the annotation service,
- add a site to the white list,
- use LaSuli in English.

Please [install LaSuli again](https://hypertopic.s3.amazonaws.com/lasuli.xpi) and let us know about your experience.

**Closed as completed by benel** 2019-05-28 16:33 UTC
